"""Initial schema

Revision ID: 3ff1921f65d9
Revises: 
Create Date: 2026-02-20 05:55:10.781415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ff1921f65d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propiedades')
    op.drop_table('processed_messages')
    op.drop_index('idx_user_facts_sender', table_name='user_facts')
    op.drop_table('user_facts')
    op.drop_table('n8n_chat_histories')
    op.alter_column('agency_configs', 'web_builder_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('bots', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'whatsapp'::character varying"))
    op.alter_column('bots', 'business_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('bots', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('bots', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('bots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('bots_instance_name_key', 'bots', type_='unique')
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_index(op.f('ix_bots_instance_name'), 'bots', ['instance_name'], unique=True)
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('calendar_events', 'notification_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint('calendar_events_property_id_fkey', 'calendar_events', type_='foreignkey')
    op.drop_constraint('calendar_events_contact_id_fkey', 'calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_events', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_history', 'sender_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('chat_history', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('chat_history', 'parts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.drop_index('idx_chat_history_sender', table_name='chat_history')
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_sender_id'), 'chat_history', ['sender_id'], unique=False)
    op.alter_column('contact_interactions', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('contact_interactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('contacts', 'last_contact_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_contacts_name', table_name='contacts')
    op.create_foreign_key(None, 'contacts', 'users', ['created_by_id'], ['id'])
    op.drop_constraint('developments_code_key', 'developments', type_='unique')
    op.create_index(op.f('ix_developments_code'), 'developments', ['code'], unique=True)
    op.alter_column('properties', 'surface',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('properties', 'visit_availability',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint('properties_code_key', 'properties', type_='unique')
    op.create_index(op.f('ix_properties_code'), 'properties', ['code'], unique=True)
    op.create_foreign_key(None, 'properties', 'users', ['assigned_agent_id'], ['id'])
    op.drop_column('properties', 'image_url')
    op.drop_column('properties', 'garages')
    op.drop_index('ix_registration_tokens_token', table_name='registration_tokens')
    op.create_unique_constraint(None, 'registration_tokens', ['token'])
    op.drop_column('registration_tokens', 'created_at')
    op.alter_column('system_configs', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_system_configs_key', table_name='system_configs')
    op.drop_index('ix_tenants_name', table_name='tenants')
    op.create_foreign_key(None, 'units', 'typologies', ['typology_id'], ['id'])
    op.drop_column('units', 'typology_name')
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'work_schedule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'break_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('users_monitoring_token_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_monitoring_token'), 'users', ['monitoring_token'], unique=True)
    op.drop_column('users', 'name')
    op.alter_column('whatsapp_buffer', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_whatsapp_buffer_sender_status', table_name='whatsapp_buffer')
    op.create_index(op.f('ix_whatsapp_buffer_id'), 'whatsapp_buffer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_buffer_id'), table_name='whatsapp_buffer')
    op.create_index('idx_whatsapp_buffer_sender_status', 'whatsapp_buffer', ['sender_id', 'status'], unique=False)
    op.alter_column('whatsapp_buffer', 'received_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_monitoring_token'), table_name='users')
    op.create_unique_constraint('users_monitoring_token_key', 'users', ['monitoring_token'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'break_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'work_schedule',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('units', sa.Column('typology_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.create_index('ix_tenants_name', 'tenants', ['name'], unique=True)
    op.create_index('ix_system_configs_key', 'system_configs', ['key'], unique=False)
    op.alter_column('system_configs', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('registration_tokens', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'registration_tokens', type_='unique')
    op.create_index('ix_registration_tokens_token', 'registration_tokens', ['token'], unique=True)
    op.add_column('properties', sa.Column('garages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_code'), table_name='properties')
    op.create_unique_constraint('properties_code_key', 'properties', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('properties', 'visit_availability',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('properties', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('properties', 'surface',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_developments_code'), table_name='developments')
    op.create_unique_constraint('developments_code_key', 'developments', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_index('ix_contacts_name', 'contacts', ['name'], unique=False)
    op.alter_column('contacts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('contacts', 'last_contact_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('contact_interactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('contact_interactions', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_history_sender_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.create_index('idx_chat_history_sender', 'chat_history', ['sender_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('chat_history', 'parts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('chat_history', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('chat_history', 'sender_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.create_foreign_key('calendar_events_contact_id_fkey', 'calendar_events', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key('calendar_events_property_id_fkey', 'calendar_events', 'properties', ['property_id'], ['id'])
    op.alter_column('calendar_events', 'notification_options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('calendar_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bots_instance_name'), table_name='bots')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.create_unique_constraint('bots_instance_name_key', 'bots', ['instance_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('bots', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bots', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bots', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('bots', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('bots', 'business_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('bots', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'whatsapp'::character varying"))
    op.alter_column('agency_configs', 'web_builder_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('n8n_chat_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='n8n_chat_histories_pkey')
    )
    op.create_table('user_facts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fact', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_facts_pkey')
    )
    op.create_index('idx_user_facts_sender', 'user_facts', ['sender_id'], unique=False)
    op.create_table('processed_messages',
    sa.Column('message_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('message_id', name='processed_messages_pkey')
    )
    op.create_table('propiedades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('contenttoembedding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='propiedades_pkey')
    )
    # ### end Alembic commands ###
